// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hioxqpptkjvvlgrzjerb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpb3hxcHB0a2p2dmxncnpqZXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDU0MDUsImV4cCI6MjA2NDM4MTQwNX0.2qh-fQok8oir0JGUlNEjitvX52c9vr41-DnxxyC_gPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);